version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: edupropyth-db-staging
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-edupropyth_staging}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - edupropyth-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/edupropyth}-backend:main
    container_name: edupropyth-backend-staging
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - PORT=3000

      # Database
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE:-edupropyth_staging}

      # JWT
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-7d}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION:-30d}

      # OAuth - Google
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}

      # OAuth - GitHub
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_CALLBACK_URL=${GITHUB_CALLBACK_URL}

      # Frontend URL
      - FRONTEND_URL=${FRONTEND_URL:-https://staging.edupropyth.com}

      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - edupropyth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-your-username/edupropyth}-frontend:main
    container_name: edupropyth-frontend-staging
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=staging
    depends_on:
      - backend
    networks:
      - edupropyth-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: edupropyth-redis-staging
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data_staging:/data
    networks:
      - edupropyth-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  edupropyth-network:
    driver: bridge

volumes:
  postgres_data_staging:
    driver: local
  redis_data_staging:
    driver: local
