# Generated by Django 5.2.7 on 2025-10-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_create_courses",
            field=models.BooleanField(default=False, verbose_name="Can create courses"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_delete_submissions",
            field=models.BooleanField(
                default=False, verbose_name="Can delete submissions"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_edit_courses",
            field=models.BooleanField(default=False, verbose_name="Can edit courses"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_grade",
            field=models.BooleanField(
                default=False, verbose_name="Can grade assignments"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="instructor_permissions_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Instructor permissions valid until"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor_viewer", "Instructor(Viewer)"),
                    ("instructor_editor", "Instructor(Editor)"),
                    ("admin", "Administrator"),
                ],
                default="student",
                max_length=20,
                verbose_name="Role",
            ),
        ),
    ]
